FLUSH PRIVILEGES;
CREATE OR REPLACE USER 'admin'@'%' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON kitties.* TO 'admin'@'%';

CREATE OR REPLACE USER 'app'@'%' IDENTIFIED BY 'app';
GRANT SELECT, INSERT, UPDATE, DELETE ON kitties.* TO 'app'@'%';

FLUSH PRIVILEGES;